# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvdvCrIfgye0-tRtzUDQT8sRs3-d_RYJ
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Titanic dataset
df = pd.read_csv("train.csv")

# (a) Basic Exploration
print("=== .info() ===")
df.info()

print("\n=== .describe() ===")
print(df.describe(include='all'))

print("\n=== .value_counts() ===")
print("\nSurvived:\n", df['Survived'].value_counts())
print("\nPclass:\n", df['Pclass'].value_counts())
print("\nSex:\n", df['Sex'].value_counts())
print("\nEmbarked:\n", df['Embarked'].value_counts())

# (b) Visualizations: Pairplot & Heatmap
sns.pairplot(df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin', 'Embarked']).dropna())
plt.suptitle("Pairplot of Key Numeric Features", y=1.02)
plt.show()
print("\n Observation: Pairplot shows that Age and Fare are right-skewed. Survived is a binary outcome.")

sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()
print("\n Observation: Fare and Pclass are negatively correlated. Survived is positively correlated with Fare and negatively with Pclass.")

# (c) Identify relationships and trends
print("\n=== Grouped Survival Rates ===")
print(df.groupby('Sex')['Survived'].mean())
print(df.groupby('Pclass')['Survived'].mean())
print(df.groupby('Embarked')['Survived'].mean())
print("\n Observation: Females and higher-class passengers had higher survival rates.")

# (d) Plot histograms, boxplots, scatterplots
# (e) Observations are provided above after each plot
sns.histplot(df['Age'].dropna(), kde=True, bins=30)
plt.title("Age Distribution")
plt.show()
print("\n Observation: Most passengers were between 20-40 years old.")

sns.boxplot(x='Pclass', y='Age', data=df)
plt.title("Age Distribution by Passenger Class")
plt.show()
print("\n Observation: 1st class passengers tend to be older than 2nd and 3rd class.")

sns.scatterplot(x='Fare', y='Age', hue='Survived', data=df)
plt.title("Fare vs Age Colored by Survival")
plt.show()
print("\n Observation: Higher fare passengers had better survival odds.")

# (f) Summary of Findings
print("\n=== Summary of Findings ===")
print("""
1. Females had a significantly higher survival rate than males.
2. 1st class passengers were more likely to survive than 2nd or 3rd class.
3. Higher fare was positively associated with survival.
4. Younger children had a better chance of survival.
5. Most passengers were in the 20–40 age range.
6. Age and Fare are not normally distributed — they are skewed.
7. Embarked location shows some influence on survival, especially from port 'C'.
""")